<Project>
    <Target Name="_CopyRemoteCoreclrTargetLibrary" 
            BeforeTargets="_ComputePublishLocation"
            Condition="'$(RemoteCoreclrTargetDir)' != ''">

        <PropertyGroup>
            <_VSRemoteCoreclrTarget>$(RemoteCoreclrTargetDir)\$(_TargetFrameworkPlatform)\$(RuntimeIdentifier)\libvsdbgremotecoreclrtarget.dylib</_VSRemoteCoreclrTarget>
            <_RemoteCoreclrTarget>$(RemoteCoreclrTargetDir)\$(_TargetFrameworkPlatform)\$(RuntimeIdentifier)\libremotecoreclrtarget.dylib</_RemoteCoreclrTarget>
        </PropertyGroup>

        <ItemGroup Condition="Exists('$(_VSRemoteCoreclrTarget)')">
            <ResolvedFileToPublish Include="$(_VSRemoteCoreclrTarget)" RelativePath="libvsdbgremotecoreclrtarget.dylib" PublishFolderType="DynamicLibrary" Kind="Dynamic" />
        </ItemGroup>
        <ItemGroup Condition="Exists('$(_RemoteCoreclrTarget)')">
            <ResolvedFileToPublish Include="$(_RemoteCoreclrTarget)" RelativePath="libremotecoreclrtarget.dylib" PublishFolderType="DynamicLibrary" Kind="Dynamic" />
        </ItemGroup>
    </Target>

    <ItemGroup Condition="'$(RemoteCoreclrTargetDir)' != '' AND '$(AndroidAttachDebugger)' == 'true'">
        <AndroidNativeLibrary Include="$(RemoteCoreclrTargetDir)\android\**\*.so" />
    </ItemGroup>
</Project>